### ISSUE TITLE
Typescript needs to be a peer dependency

### ISSUE THREAD

**Issue by jonnysamps** [prisma/serverless-plugin-typescript#112]
Hi there, thank you so much for developing this plugin, it is awesome! However, I have a major problem: I can only use TS 2.* because it is a direct dependency of the plugin. We need to have `typescript` be peer dependency in `package.json` so we can use whatever version of TS we see fit.

**Comment by thekevinbrown** [comment]
I would like to use typescript v3. Any chance of doing this?

**Comment by JackCuthbert** [comment]
This has been resolved, please open a new issue if there's something I missed :smiley:
