### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by Crazometer** [prisma/serverless-plugin-typescript#119]
Is this repo still being actively developed? Do you need help maintaining it?

A few of the PRs look to be easy fixes for some issues people are having.

@schickling, @kandros

**Comment by thomasruiz** [comment]
I agree. Please don't let this project die: using webpack to build server-side code is non-sense.

**Comment by kandros** [comment]
personally I'm not using serverless at the moment, worth try asking some prisma members to be added as maintainters. You can find them at https://slack.prisma.io/

**Comment by divyenduz** [comment]
Thanks for raising this issue. We are looking for long term maintainers for this project. If you are interested, please let me know 🙌

**Comment by JackCuthbert** [comment]
Hey @divyenduz I'm happy to take a look into maintaining this. I use typescript with serverless enough in my own projects that a plugin like this is super valuable for me.

**Comment by divyenduz** [comment]
@JackCuthbert Let us get in touch to talk more about this, can you find me on our public slack (slack.prisma.io) or write to me at `singh@prisma.io` to schedule a call?

**Comment by divyenduz** [comment]
@JackCuthbert would help us maintain this project  🎉🙌 

We are happy to have more people helping out with this but I am closing this issue for now. Please re-open a new issue if you think that this is still relevant
