### ISSUE TITLE
not including js files on build (running just tsc does)

### ISSUE THREAD

**Issue by AJ-N** [prisma/serverless-plugin-typescript#155]
When I deploy (via serverless deploy) or run locally (via serverless offline), the plugin is not correctly including my javascript files.
allowJs is set to true

However, if I first run a tsc, the js files are correctly added to the .build directory
my tsconfig
```json
{
  "compilerOptions": {
    "preserveConstEnums": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "target": "es5",
    "outDir": ".build",
    "moduleResolution": "node",
    "lib": ["es2015"],
    "rootDir": "./",
    "allowJs": true,
    "typeRoots": [ "./typings", "./node_modules/@types"],
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "typings",
  ]
}
```

my src directory:
```bash
$ ls ./src
handler.ts
utils.js
```

with JUST 'sls deploy':
```bash
$ ls .build/src
handler.js
handler.js.map
```

if I run 'tsc' first:
```bash
$ ls .build/src
handler.js
handler.js.map
utils.js
utils.js.map
```

package.json
```json
  "dependencies": {
    ...
    "serverless-plugin-typescript": "^1.1.7",
  },
  "devDependencies": {
     ...
    "@types/node": "^10.12.18",
    "serverless-offline": "^5.7.2",
    "ts-loader": "^5.3.3",
    "typescript": "^3.2.4"
  },
```

serverless version: 1.42.3
tsc version: 3.4.5

**Comment by AJ-N** [comment]
I think this was an issue with webpack and not properly disabling it

**Comment by sandromartis** [comment]
I have the same issue.

Running `tsc` includes all the files specified in `tsconfig.json`.

However, when I run `serverless package` it does not include the javascript files, they are missing from the `.build` folder and then also from the zipped package.

Is there a solution to that problem?

**Comment by ablankenship10** [comment]
Same issue, @aj-n do you know how you resolved the problem?

**Comment by ajn-sbd** [comment]
I don't unfortunately. Eventually I moved to using [serverless-esbuild](https://www.serverless.com/plugins/serverless-esbuild) and that solved all my typescipt building issues.

**Comment by ablankenship10** [comment]
I was able to solve it by dropping this package which builds using the `typescript` package's createProgram function and instead used `tsc` directly to build with my handler pointed at the build directory. It's not perfect but it works to get a legacy platform off expensive servers and onto serverless.
