### ISSUE TITLE
Plugin throws `Cannot read property 'prepare' of undefined` when recompiling

### ISSUE THREAD

**Issue by ValiDraganescu** [prisma/serverless-plugin-typescript#162]
Plugin throws `Cannot read property 'prepare' of undefined` when recompiling

This happens in version 1.1.8 after updating some code and te watcher kicks in to recompile.

**Comment by JackCuthbert** [comment]
This is my bad, oops. Have repro'd this, will sort this asap!

**Comment by ValiDraganescu** [comment]
You have been fast, 10x!!
