### ISSUE TITLE
Support non TS handlers

### ISSUE THREAD

**Issue by ro-savage** [prisma/serverless-plugin-typescript#78]
This plugin should handle having handles with both the .js and .ts extension, and simply not transpile the .js files.

I wanted to convert my current serverless project to TS, and only rename TS files once I've updated them.

Currently we get an error that looks like
```
Serverless: Using local tsconfig.json
{ file: undefined,
  start: undefined,
  length: undefined,
  messageText: 'File \'myfunction.ts\' not found.',
  category: 1,
  code: 6053 }

  Type Error ---------------------------------------------

  Cannot read property 'getLineAndCharacterOfPosition' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by ro-savage** [comment]
Along the same lines, it doesn't appear to follow imports of non-ts files.

```
[ 'Error: Cannot find module \'./helpers/helpers\'',
  'at Function.Module._resolveFilename (module.js:555:15)',
  'at Function.Module._load (module.js:482:25)',
  'at Module.require (module.js:604:17)',
...
```

Renaming `helpers.js` to `helpers.ts` solves the issue

**Comment by ro-savage** [comment]
PR #79 fixes this by allowing importing either the `.js` or the `.ts` based on what exists.

**Comment by MikeBlair** [comment]
👍 This would be useful for us as well.

**Comment by kiesel** [comment]
I'd like to see this supported, too. Usecase: we use custom authorizers that we ship as a npm module; the code is written in TypeScript and transpiled to JavaScript, but then it cannot be used because it won't be picked up.

The workaround currently is to ship it as npm module, but include the source and reference the source file in the `handler:` line, thus having the main project's build re-build the authorizer again.

**Comment by Pithikos** [comment]
Same issue when trying to use a mix of functions in Python and Javascript. It tries to transpile python functions

```
{ file: undefined,
  start: undefined,
  length: undefined,
  messageText: 'File \'api.handler.ts\' not found.',
  category: 1,
  code: 6053,
  reportsUnnecessary: undefined }
```
