### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by DaleJefferson** [prisma/serverless-plugin-typescript#89]
Does this plugin work on windows?

I get the following error when I attempt to use this plugin.

```
EPERM: operation not permitted, symlink 'C:\Users\Dale\Development\www.dalejefferson.com\node_modules' -> 'C:\Users\Dale\Development\www.dalejefferson.com\.build\node_modules'
```

**Comment by cspotcode** [comment]
I managed to get past that error, but `excludeDevDependencies` is not excluding transitive dependencies.  So I think the answer is no, not at the moment.

**Comment by j-murph** [comment]
Running as administrator fixed it for me.

**Comment by dls314** [comment]
Is there any update on this, or related issues (like #23, #45, #90) around using serverless-plugin-typescript on windows?

For whatever reason, the workaround that previously worked (being an administrator) isn't working for me on Windows 10 build 17134.

**Comment by GhostfromTexas** [comment]
We've fixed this issue and created a PR for it, however this project hasn't been updated really since February.

https://github.com/prismagraphql/serverless-plugin-typescript/pull/103

There are 2 current issues people get with the symbolic link problem. The permissions problem and a EPRM scandir problem because the link is invalid. 

We created an NPM module with our fix in it for those that want to use it

https://www.npmjs.com/package/@hewmen/serverless-plugin-typescript

**Comment by didac-wh** [comment]
@GhostfromTexas I appreciate your effort. Unfortunately it doesn't seem to work for me, as I'm getting the exact same error as before:

EPERM: operation not permitted, symlink '[source_dir]\package.json' -> '[source_dir]\.build\package.json'

I basically installed your NPM package and imported it in my severless.yml plugins sections, removing the old serverless-plugin-typescript.

Don't know if I'm doing something wrong...

**Comment by GhostfromTexas** [comment]
Hmm - Try an elevated console and see if that works. We might have only solved part of that problem

**Comment by dls314** [comment]
Mixed experiences for me, @hewmen/serverless-plugin-typescript has no errors for me when packaging from windows, but the packaging also doesn't correctly exclude dev dependencies (either on windows or linux)

**Comment by GhostfromTexas** [comment]
I wonder if the dev-dependency exclusion is on the original version as well. The only problem pushed a change for was the symbolic linking. Excluding dev dependencies might be an unrelated bug, or maybe a bug we caused?

**Comment by dls314** [comment]
I don't think the changes made anything worse, but I only hit the EPERM scandir problem when I was trying to exclude dev dependencies, so it's all somewhat related.

fwiw/ the underlying calls to `npm ls --dev=true --parseable=true --long=false --silent` and  `npm ls --prod=true --parseable=true --long=false --silent` being used by zipService.js don't seem to work the same through a symlink on Windows (even with the fix introduced in https://github.com/prismagraphql/serverless-plugin-typescript/pull/103)

https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/zipService.js#L166

It doesn't seem to work the same; when I interrupt `serverless package` on windows and then run the npm ls command from the root or .build directory, I get different results depending on being in the .build or root directory.

**Comment by GhostfromTexas** [comment]
Hmm.. We exclude dev dependencies on ours as well and don't see the EPERM scandir problem anymore with the HEWMEN version. So looks like there are some more edge cases that are causing the same problems to pop up.

What we saw originally was the build failing at the packaging step, and from the looks of the .build folder structure, the symlink to the "node_modules" directory was created as a file and not a folder.

So looking like there are 3-4 issues then... weee!

**Comment by dls314** [comment]
Packaging on Windows is producing much smaller packages when I set the NODE_PRESERVE_SYMLINKS=1 environment variable. I'm not yet certain that's fixed dev dependency exclusion, but it seems to have so far.
