### ISSUE TITLE
Module aliases are not interpreted

### ISSUE THREAD

**Issue by jonnyasmar** [prisma/serverless-plugin-typescript#96]
I'm using a **tsconfig.json** that contains module aliases like so:

```
    "paths": {
      "actions/*": ["src/actions/*"],
      "components/*": ["src/components/*"],
      "reducers/*": ["src/reducers/*"],
      "services/*": ["src/services/*"],
      "styles/*": ["src/styles/*"],
      "utils/*": ["src/utils/*"],
      "views/*": ["src/views/*"]
    }
```

Unfortunately, this plugin does not interpret these aliases. So doing something like:

`import { someCoolUtil } from 'utils/someCoolUtil'`

Ends up compiling to:

`var someCoolUtil_1 = require("utils/someCoolUtil");`

Not sure if this is a bug or an issue with my implementation, but these path mappings work perfectly fine when my project is compiled using **awesome-typescript-loader** in Webpack.

**Comment by pie6k** [comment]
I have the same issue

**Comment by jonnyasmar** [comment]
So, I solved this problem in a pretty trivial manner...

I got rid of serverless-plugin-typescript and created a bundle of my TS using Webpack. The resulting JS bundle is then deployed via sls deploy.

Simple solution, but doesn't leverage this plugin at all.

**Comment by leejh3224** [comment]
I found out that `baseUrl` option in `tsconfig.json` also doesn't work.

So I replaced all the `import` statement with relative syntax :(

**Comment by manuabhijit** [comment]
> So, I solved this problem in a pretty trivial manner...
> 
> I got rid of serverless-plugin-typescript and created a bundle of my TS using Webpack. The resulting JS bundle is then deployed via sls deploy.
> 
> Simple solution, but doesn't leverage this plugin at all.

Please be more detailed. I am facing the same issue.

**Comment by JackCuthbert** [comment]
My understanding is that this issue is related to TypeScript and not this plugin. Typescript does indeed support module path aliases during compilation, but will not emit these aliased paths, see https://github.com/Microsoft/TypeScript/issues/10866.

Please feel free to re-open a new issue if you think it's still relevant 😄

**Comment by trungtin** [comment]
As I can see from that issue, this will be non-fixed from typescript team.

One alternative is using something like https://github.com/ilearnio/module-alias/, but because of each function is compiled separately so is there a way to prepend the register code `require('module-alias/register')` before every function?

**Comment by ericmaicon** [comment]
@trungtin have you found a solution?

**Comment by trungtin** [comment]
@ericmaicon nope, I switch to serverless-webpack for the moment.

**Comment by joshdura** [comment]
Has anyone found a solution to this?

**Comment by joaodfmota** [comment]
I'm using aliases with
https://github.com/AnomalyInnovations/serverless-bundle

**Comment by brothatru** [comment]
If you are using serverless-webpack (installed by default if you used `sls create --template aws-nodejs-typescript`) 

 In your **webpack.config.js**
```
// webpack.config.js
resolve: {
  extensions: ['.ts'],
  alias: {
    '@app': path.resolve(__dirname, './src'),
  },
},

// tsconfig.json
"baseUrl": "./src/",
"paths": {
    "@app/*": ["./*"]
},
```

[Found in this thread](https://github.com/serverless-heaven/serverless-webpack/issues/591#issuecomment-658286287)

**Comment by karltaylor** [comment]
> I'm using aliases with
> https://github.com/AnomalyInnovations/serverless-bundle

Can you elaborate @joaodfmota? I'm trying to find a simple solution, I've added the following to `serverless.yml` to no success

```
custom:
  bundle:
    stats: false
    aliases:
      - src: "./"
```

**Comment by mr-piratman** [comment]
this is working for me
https://www.npmjs.com/package/serverless-tscpaths

just 
`$ yarn add serverless-tscpaths -D`

and in your serverless.yml
```
plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths # should be after serverless-plugin-typescript
 ```
